version: 'latest'

services:
  app:
    build:
      context: ./app
    environment:
      - DB_INFO=${DB_DEV}
      - DEBUG=True
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - SECRET_KEY=${SECRET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=8000
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
