name: APP EC2 Deploy

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "app/**"
  pull_request:
    branches: ["main"]
    paths:
      - "app/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy in EC2
        env:
          KEY: ${{ secrets.KEY  }}
          HOST: ${{ secrets.HOST  }}
          USER: ${{ secrets.USER  }}
          PATH: ${{ secrets.PATH }}

        run: |
          echo "$KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i key ${USER}@${HOST} '

            cd ${PATH} &&
            git pull &&
            docker-compose -f docker-compose-prod.yml build app &&
            docker-compose -f docker-compose-prod.yml up -d --no-deps app
          '
