name: APP EC2 Deploy

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "app/**"
  pull_request:
    branches: ["main"]
    paths:
      - "app/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Deploy in EC2
        env:
          PRIVATE_KEY: ${{ secrets.KEY  }}
          HOST: ${{ secrets.HOST  }}
          USER: ${{ secrets.USER  }}
          DEPLOY_PATH: ${{ secrets.PATH }}

        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
            DEPLOY_PATH='"${DEPLOY_PATH}"' # Define DEPLOY_PATH in remote shell
            cd $DEPLOY_PATH &&
            git pull &&
            docker-compose -f docker-compose-prod.yml build app &&
            docker-compose -f docker-compose-prod.yml up -d --no-deps app
          '
